name: sub_account_setup

env:
  SNOWSQL_ACCOUNT: ${{ env.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ env.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ env.SNOWSQL_PWD }}
  SNOWSQL_ROLE: ${{ env.SNOWSQL_ROLE }}
  SNOWSQL_WAREHOUSE: ${{ env.SNOWSQL_WAREHOUSE }}
  SNOWSQL_DATABASE: ${{ env.TGT_DB }}
  SNOWSQL_SCHEMA: ${{ env.TGT_SCHEMA }}
  SNOWSQL_RAW_DB: ${{ env.SRC_DB }}
  SNOWSQL_SRC_SCHEMA: ${{ env.SRC_SCHEMA }}
  SNOWSQL_CUSTOMER: ${{ env.CUST_NAME }}
  SNOWSQL_ADMIN_PSW: ${{ env.ADMIN_PASSWORD }}

on:
  workflow_dispatch:

jobs:
  executequery:
    name: Sub account setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash

      - name: Install SnowSQL
        run: |
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Test installation
        run: ~/snowflake/snowsql -v

      - name: Variable Substitution
        run: echo "variable_substitution=true" | tee -a ~/.snowsql/config

      - name: Create Snowflake Account and Save JSON Response to File
        run: |
          ~/snowflake/snowsql <<EOF > json_response.json
          CREATE ACCOUNT myaccount10
          ADMIN_NAME = admin
          ADMIN_PASSWORD = '${{ env.ADMIN_PASSWORD }}'
          EMAIL = 'myemail@myorg.org'
          MUST_CHANGE_PASSWORD = FALSE
          EDITION = enterprise;
          EOF

      - name: Display JSON Response from File
        run: cat json_response.json

      - name: Extract Values from JSON Response
        run: |
          # Display values directly from the JSON response file
          echo "accountLocator: $(jq -r '.accountLocator' json_response.json)"
          echo "accountLocatorUrl: $(jq -r '.accountLocatorUrl' json_response.json)"
          echo "accountName: $(jq -r '.accountName' json_response.json)"
          echo "url: $(jq -r '.url' json_response.json)"
          echo "edition: $(jq -r '.edition' json_response.json)"
