name: Authentication

env:
  SNOWSQL_ACCOUNT: ${{ vars.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ vars.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ vars.SNOWSQL_PWD }}
  SNOWSQL_ROLE: ${{ vars.SNOWSQL_ROLE }}
  SNOWSQL_WAREHOUSE: ${{ vars.SNOWSQL_WAREHOUSE }}
  SNOWSQL_DATABASE: ${{ vars.TGT_DB }}
  SNOWSQL_SCHEMA: ${{ vars.TGT_SCHEMA }}
  SNOWSQL_RAW_DB: ${{ vars.SRC_DB }}
  SNOWSQL_SRC_SCHEMA: ${{ vars.SRC_SCHEMA }}
  SNOWSQL_CUST_NAME: ${{ vars.CUST_NAME }}
  SNOWSQL_ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
  SNOWSQL_CUST_EMAIL: ${{ vars.CUST_EMAIL }}
  SNOWSQL_CUST_DB: ${{ vars.CUST_DB }}
  SNOWSQL_CUST_SCHEMA: ${{ vars.CUST_SCHEMA }}
  SNOWSQL_MAIN_LOCATOR: ${{ vars.MAIN_LOCATOR }}

on:
  workflow_dispatch:

jobs:
  executequery:
    name: Sub account setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash

      - name: Install SnowSQL
        run: |
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Test installation
        run: ~/snowflake/snowsql -v

      - name: Variable Substitution
        run: echo "variable_substitution=true" | tee -a ~/.snowsql/config

      - name: Setup SnowSQL and Create Snowflake Account
        run: |
          ~/snowflake/snowsql <<EOF
          USE ROLE ACCOUNTADMIN;
          CREATE OR REPLACE SHARE ${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE;
          USE DATABASE ${{ env.SNOWSQL_CUST_DB }};
          GRANT USAGE ON DATABASE ${{ env.SNOWSQL_CUST_DB }} TO SHARE "${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE";
          GRANT USAGE ON SCHEMA ${{ env.SNOWSQL_CUST_SCHEMA }} TO SHARE "${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE";
          GRANT SELECT ON ALL TABLES IN SCHEMA ${{ env.SNOWSQL_CUST_DB }}.${{ env.SNOWSQL_CUST_SCHEMA }} TO SHARE "${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE";
          EOF

          ~/snowflake/snowsql <<EOF > account_details.txt
          CREATE ACCOUNT ${{ env.SNOWSQL_CUST_NAME }}
          ADMIN_NAME = admin
          ADMIN_PASSWORD = "${{ env.SNOWSQL_ADMIN_PASSWORD }}"
          EMAIL = '${{ env.SNOWSQL_CUST_EMAIL }}'
          MUST_CHANGE_PASSWORD = FALSE
          EDITION = enterprise;
          EOF
          cat account_details.txt | wc -l
          head -n 6 account_details.txt | tail -n 1 > url.json
          cat url.json
          # Remove leading and trailing "|" from the file
          sed -i 's/^ *| *//; s/ *| *$//' url.json
          Locator=`jq -r '.accountLocator' url.json`
          echo ""
          echo "Locator: $Locator"
          accountLocatorUrl=`jq -r '.accountLocatorUrl' url.json`
          echo ""
          echo "accountLocatorUrl: $accountLocatorUrl"
          trimmed_url=$(echo "$accountLocatorUrl" | sed 's#https://##;s#\.snowflakecomputing\.com##')
          echo "$trimmed_url"
          ~/snowflake/snowsql -r ACCOUNTADMIN -q "ALTER SHARE \"${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE\" ADD ACCOUNTS = $Locator;"
          SNOWSQL_ACCOUNT="$trimmed_url"
          SNOWSQL_USER=Admin
          SNOWSQL_ROLE=SYSADMIN
          SNOWSQL_PWD="${{ env.SNOWSQL_ADMIN_PASSWORD }}"
          ~/snowflake/snowsql << EOF
          select current_account();
          USE ROLE SYSADMIN;
          CREATE OR REPLACE WAREHOUSE ${{ env.SNOWSQL_CUST_NAME }}_WH;
          USE ROLE SECURITYADMIN;
          CREATE OR REPLACE ROLE ${{ env.SNOWSQL_CUST_NAME }};
          CREATE OR REPLACE USER ${{ env.SNOWSQL_CUST_NAME }} PASSWORD='Welcome@123';
          GRANT ROLE ${{ env.SNOWSQL_CUST_NAME }} TO USER ${{ env.SNOWSQL_CUST_NAME }};
          USE ROLE SYSADMIN;
          GRANT USAGE ON WAREHOUSE ${{ env.SNOWSQL_CUST_NAME }}_WH TO ROLE ${{ env.SNOWSQL_CUST_NAME }};
          USE ROLE ACCOUNTADMIN;
          CREATE OR REPLACE DATABASE ADVARRA_ONCORE_RAW FROM SHARE ${{ env.SNOWSQL_MAIN_LOCATOR }}.${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE;
          GRANT IMPORTED PRIVILEGES ON DATABASE ADVARRA_ONCORE_RAW TO ROLE ${{ env.SNOWSQL_CUST_NAME }};
          GRANT IMPORTED PRIVILEGES ON DATABASE ADVARRA_ONCORE_RAW TO ROLE SYSADMIN;
          USE ROLE SYSADMIN;
          CREATE OR REPLACE DATABASE ADVARRA_CLOUD_ONCORE;
          GRANT USAGE ON DATABASE ADVARRA_CLOUD_ONCORE TO ROLE ${{ env.SNOWSQL_CUST_NAME }};
          CREATE OR REPLACE DATABASE ADVARRA_CLOUD_ONCORE_MODELLED;
          GRANT USAGE ON DATABASE ADVARRA_CLOUD_ONCORE_MODELLED TO ROLE ${{ env.SNOWSQL_CUST_NAME }};
          CREATE OR REPLACE DATABASE ADVARRA_ONCORE_WORKSPACE;
          CREATE OR REPLACE SCHAMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE;
          GRANT USAGE ON SCHEMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }};
          GRANT CREATE TABLE ON SCHEMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }};
          GRANT CREATE VIEW ON SCHEMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }};
          EOF
