name: Authentication

env:
  SNOWSQL_ACCOUNT: ${{ vars.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ vars.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ vars.SNOWSQL_PWD }}
  SNOWSQL_ROLE: ${{ vars.SNOWSQL_ROLE }}
  SNOWSQL_CUST_NAME: ${{ vars.CUST_NAME }}
  SNOWSQL_ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
  SNOWSQL_CUST_SCHEMA: ${{ vars.CUST_SCHEMA }}

on:
  workflow_dispatch:

jobs:
  executequery:
    name: Sub account setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash

      - name: Install SnowSQL
        run: |
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Test installation
        run: ~/snowflake/snowsql -v

      - name: Variable Substitution
        run: echo "variable_substitution=true" | tee -a ~/.snowsql/config

      - name: Setup SnowSQL and Create Snowflake Account
        run: |
          ~/snowflake/snowsql <<EOF
          USE ROLE ACCOUNTADMIN;
          CREATE OR REPLACE SHARE ${{ env.SNOWSQL_CUST_NAME }}_SHARE;
          USE DATABASE ${{ env.SNOWSQL_CUST_DB }};
          GRANT USAGE ON DATABASE ${{ env.SNOWSQL_CUST_DB }} TO SHARE "${{ env.SNOWSQL_CUST_NAME }}_SHARE";
          GRANT USAGE ON SCHEMA ${{ env.SNOWSQL_CUST_SCHEMA }} TO SHARE "${{ env.SNOWSQL_CUST_NAME }}_SHARE";
          GRANT SELECT ON ALL TABLES IN SCHEMA ${{ env.SNOWSQL_CUST_DB }}.${{ env.SNOWSQL_CUST_SCHEMA }} TO SHARE "${{ env.SNOWSQL_CUST_NAME }}_SHARE";
          EOF

          ~/snowflake/snowsql <<EOF > account_details.txt
          CREATE ACCOUNT ${{ env.SNOWSQL_CUST_NAME }}
          ADMIN_NAME = admin
          ADMIN_PASSWORD = "${{ env.SNOWSQL_ADMIN_PASSWORD }}"
          EMAIL = '${{ env.SNOWSQL_CUST_EMAIL }}'
          MUST_CHANGE_PASSWORD = FALSE
          EDITION = enterprise;
          EOF
          cat account_details.txt | wc -l
          head -n 6 account_details.txt | tail -n 1 > url.json
          cat url.json
          # Remove leading and trailing "|" from the file
          sed -i 's/^ *| *//; s/ *| *$//' url.json
          Locator=`jq -r '.accountLocator' url.json`
          echo ""
          echo "Locator: $Locator"
          accountLocatorUrl=`jq -r '.accountLocatorUrl' url.json`
          echo ""
          echo "accountLocatorUrl: $accountLocatorUrl"
          ~/snowflake/snowsql -r ACCOUNTADMIN -q "ALTER SHARE \"${{ env.SNOWSQL_CUST_NAME }}_SHARE\" ADD ACCOUNTS = $Locator;"
          SNOWSQL_ACCOUNT = $accountLocatorUrl
          SNOWSQL_USER = Admin
          SNOWSQL_PWD =${{ env.SNOWSQL_ADMIN_PASSWORD }}
          ~/snowflake/snowsql << EOF
          select current_account();
          EOF
          
          
