name: old_code_copy

env:
  SNOWSQL_ACCOUNT: ${{ vars.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ vars.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ vars.SNOWSQL_PWD }}
  SNOWSQL_ROLE: ${{ vars.SNOWSQL_ROLE }}
  SNOWSQL_WAREHOUSE: ${{ vars.SNOWSQL_WAREHOUSE }}
  SNOWSQL_DATABASE: ${{ vars.TGT_DB }}
  SNOWSQL_SCHEMA: ${{ vars.TGT_SCHEMA }}
  SNOWSQL_RAW_DB: ${{ vars.SRC_DB }}
  SNOWSQL_SRC_SCHEMA: ${{ vars.SRC_SCHEMA }}
  SNOWSQL_CUST_NAME: ${{ vars.CUST_NAME }}
  SNOWSQL_ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
  SNOWSQL_CUST_EMAIL: ${{ vars.CUST_EMAIL }}
  SNOWSQL_CUST_DB: ${{ vars.CUST_DB }}
  SNOWSQL_CUST_SCHEMA: ${{ vars.CUST_SCHEMA }}
  SNOWSQL_MAIN_LOCATOR: ${{ vars.MAIN_LOCATOR }}

on:
  workflow_dispatch:

jobs:
  executequery:
    name: Sub account setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash

      - name: Install SnowSQL
        run: |
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Test installation
        run: ~/snowflake/snowsql -v

      - name: Variable Substitution
        run: echo "variable_substitution=true" | tee -a ~/.snowsql/config

      - name: Setup SnowSQL and Create Snowflake Account
        run: |
          ~/snowflake/snowsql <<EOF
          USE ROLE ACCOUNTADMIN;
          CREATE OR REPLACE SHARE ${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE;
          USE DATABASE RAW_CLOUD_ONCORE;
          GRANT USAGE ON DATABASE RAW_CLOUD_ONCORE TO SHARE ${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE;
          GRANT USAGE ON SCHEMA RAW_CLOUD_ONCORE.${{ env.SNOWSQL_CUST_SCHEMA }} TO SHARE ${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE;
          GRANT SELECT ON ALL TABLES IN SCHEMA RAW_CLOUD_ONCORE.${{ env.SNOWSQL_CUST_SCHEMA }} TO SHARE ${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE;
          EOF

          ~/snowflake/snowsql <<EOF > account_details.txt
          CREATE ACCOUNT ${{ env.SNOWSQL_CUST_NAME }}_ADVARRA_SUB_ACCOUNT
          ADMIN_NAME = admin
          ADMIN_PASSWORD = "${{ env.SNOWSQL_ADMIN_PASSWORD }}"
          EMAIL = '${{ env.SNOWSQL_CUST_EMAIL }}'
          MUST_CHANGE_PASSWORD = FALSE
          EDITION = enterprise;
          EOF
          cat account_details.txt | wc -l
          head -n 6 account_details.txt | tail -n 1 > url.json
          cat url.json
          # Remove leading and trailing "|" from the file
          sed -i 's/^ *| *//; s/ *| *$//' url.json
          Locator=`jq -r '.accountLocator' url.json`
          echo ""
          echo "Locator: $Locator"
          accountLocatorUrl=`jq -r '.accountLocatorUrl' url.json`
          echo ""
          echo "accountLocatorUrl: $accountLocatorUrl"
          sub_acc_url=$(echo "$accountLocatorUrl" | sed 's#https://##;s#\.snowflakecomputing\.com##')
          echo "sub_acc_url: $sub_acc_url"
          ~/snowflake/snowsql -r ACCOUNTADMIN -q "ALTER SHARE ${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE ADD ACCOUNTS = $Locator;"
          SNOWSQL_ACCOUNT="$sub_acc_url"
          SNOWSQL_USER=Admin
          SNOWSQL_ROLE=SYSADMIN
          SNOWSQL_PWD="${{ env.SNOWSQL_ADMIN_PASSWORD }}"
          ~/snowflake/snowsql << EOF
          select current_account();
          USE ROLE SYSADMIN;
          CREATE OR REPLACE WAREHOUSE ${{ env.SNOWSQL_CUST_NAME }}_WH;
          USE ROLE SECURITYADMIN;
          CREATE OR REPLACE ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          CREATE OR REPLACE USER ${{ env.SNOWSQL_CUST_NAME }}_USER PASSWORD='Welcome@123';
          GRANT ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE TO USER ${{ env.SNOWSQL_CUST_NAME }}_USER;
          USE ROLE SYSADMIN;
          GRANT USAGE ON WAREHOUSE ${{ env.SNOWSQL_CUST_NAME }}_WH TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          USE ROLE ACCOUNTADMIN;
          CREATE OR REPLACE DATABASE RAW_CLOUD_ONCORE FROM SHARE ${{ env.SNOWSQL_MAIN_LOCATOR }}.${{ env.SNOWSQL_CUST_NAME }}_ONCORE_RAW_SHARE;
          GRANT IMPORTED PRIVILEGES ON DATABASE RAW_CLOUD_ONCORE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          GRANT IMPORTED PRIVILEGES ON DATABASE RAW_CLOUD_ONCORE TO ROLE SYSADMIN;
          USE ROLE SYSADMIN;
          CREATE OR REPLACE DATABASE MODELLED_CLOUD_ONCORE;
          GRANT USAGE ON DATABASE MODELLED_CLOUD_ONCORE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          CREATE OR REPLACE DATABASE WORKSPACE_ADVARRA_ONCORE;
          CREATE OR REPLACE SCHEMA WORKSPACE_ADVARRA_ONCORE.VIEWS_WORKSPACE;
          GRANT USAGE ON DATABASE WORKSPACE_ADVARRA_ONCORE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          GRANT USAGE ON SCHEMA WORKSPACE_ADVARRA_ONCORE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          GRANT CREATE VIEW ON SCHEMA WORKSPACE_ADVARRA_ONCORE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          EOF
