name: Reader_account_setup

env:
  SNOWSQL_ACCOUNT: ${{ vars.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ vars.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ vars.SNOWSQL_PWD }}
  SNOWSQL_ROLE: ${{ vars.SNOWSQL_ROLE }}
  SNOWSQL_WAREHOUSE: ${{ vars.SNOWSQL_WAREHOUSE }}
  SNOWSQL_CUST_SHORT_NAME: ${{ vars.CUST_SHORT_NAME }}
  SNOWSQL_ADMIN_PASSWORD: ${{ vars.ADMIN_PASSWORD }}
  
on:
  workflow_dispatch:
    inputs:
      admin_password:
        description: 'Admin Password'
        required: true
      cust_short_name:
        description: 'Customer Short Name'
        required: true

jobs:
  executequery:
    name: reader_account
    runs-on: ubuntu-latest
    steps:
      - name: Input Admin Password and Customer Short Name
        if: github.event_name == 'workflow_dispatch'
        id: input_step
        run: |
          echo "SNOWSQL_CUST_SHORT_NAME=${{ github.event.inputs.cust_short_name }}" >> $GITHUB_ENV
          echo "SNOWSQL_ADMIN_PASSWORD=${{ github.event.inputs.admin_password }}" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v2

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash

      - name: Install SnowSQL
        run: |
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Test installation
        run: ~/snowflake/snowsql -v

      - name: Variable Substitution
        run: echo "variable_substitution=true" | tee -a ~/.snowsql/config

      - name: create snowflake reader account
        run: |
          ~/snowflake/snowsql <<EOF > Reader_details.txt
          USE ROLE ACCOUNTADMIN;
          CREATE MANAGED ACCOUNT $SNOWSQL_CUST_SHORT_NAME
            ADMIN_NAME = ADMIN
            ADMIN_PASSWORD = "$SNOWSQL_ADMIN_PASSWORD"
            TYPE = READER;
          EOF
          cat Reader_details.txt | wc -l
          head -n 12 Reader_details.txt | tail -n 1 > url.json
          cat url.json
          # Remove leading and trailing "|" from the file
          sed -i 's/^ *| *//; s/ *| *$//' url.json
          reader_url=$(jq -r '.url' url.json)
          echo ""
          echo "reader_url: $reader_url"
          reader_url_trimmed=$(echo "$reader_url" | sed 's#https://##;s#\.snowflakecomputing\.com##')
          echo "reader_url_trimmed: $reader_url_trimmed"
          sleep 60
          SNOWSQL_ACCOUNT="$reader_url_trimmed"
          SNOWSQL_USER=ADMIN
          SNOWSQL_ROLE=ACCOUNTADMIN
          SNOWSQL_PWD="$SNOWSQL_ADMIN_PASSWORD"
          ~/snowflake/snowsql << EOF
          select current_account();
          create warehouse "${{ env.SNOWSQL_CUST_SHORT_NAME }}_WH";
          create or replace role EVAL_READER_ROLE;
          create or replace role EDC_READER_ROLE;
          create or replace role ONCORE_READER_ROLE;
          grant usage on warehouse "${{ env.SNOWSQL_CUST_SHORT_NAME }}_WH" to role EVAL_READER_ROLE;
          grant usage on warehouse "${{ env.SNOWSQL_CUST_SHORT_NAME }}_WH" to role EDC_READER_ROLE;
          grant usage on warehouse "${{ env.SNOWSQL_CUST_SHORT_NAME }}_WH" to role ONCORE_READER_ROLE;
          grant role EVAL_READER_ROLE to user admin;
          grant role EDC_READER_ROLE to user admin;
          grant role ONCORE_READER_ROLE to user admin;
          create database WORKSPACE_CLOUD_ONCORE;
          create schema WORKSPACE_CLOUD_ONCORE.VIEWS_WORKSPACE;
          grant usage on database WORKSPACE_CLOUD_ONCORE to role ONCORE_READER_ROLE;
          grant usage on schema WORKSPACE_CLOUD_ONCORE.VIEWS_WORKSPACE to role ONCORE_READER_ROLE;
          grant create view on schema WORKSPACE_CLOUD_ONCORE.VIEWS_WORKSPACE to role ONCORE_READER_ROLE;
          EOF
