name: sub_account_setup

env:
  SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
  SNOWSQL_MAIN_LOCATOR: ${{ vars.MAIN_LOCATOR }}
  SNOWSQL_CUST_NAME: ${{ vars.CUST_NAME }}

on:
  workflow_dispatch:

jobs:
  executequery:
    name: Sub account setup Job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download SnowSQL
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash

      - name: Install SnowSQL
        run: |
          SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash

      - name: Test installation
        run: ~/snowflake/snowsql -v

      - name: Variable Substitution
        run: echo "variable_substitution=true" | tee -a ~/.snowsql/config

      - name: Setup SnowSQL and Create Snowflake Account
        run: |
          ~/snowflake/snowsql <<EOF
          USE ROLE SYSADMIN;
          CREATE OR REPLACE WAREHOUSE ${{ env.SNOWSQL_CUST_NAME }}_WH;
          USE ROLE SECURITYADMIN;
          CREATE OR REPLACE ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          CREATE OR REPLACE USER ${{ env.SNOWSQL_CUST_NAME }} PASSWORD='Welcome@123' DEFAULT_ROLE=${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          USE ROLE SYSADMIN;
          GRANT USAGE ON WAREHOUSE ${{ env.SNOWSQL_CUST_NAME }}_WH TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          USE ROLE ACCOUNTADMIN;
          CREATE OR REPLACE DATABASE ADVARRA_ONCORE_RAW FROM SHARE ${{ env.SNOWSQL_MAIN_LOCATOR }}.${{ env.SNOWSQL_CUST_NAME }}_SHARE;
          GRANT USAGE ON DATABASE ADVARRA_ONCORE_RAW TO ROLE ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          USE ROLE SYADMIN;
          CREATE OR REPLACE DATABASE ADVARRA_ONCORE_WORKSPACE;
          CREATE OR REPLACE SCHEMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE;
          GRANT USAGE ON DATABASE ADVARRA_ONCORE_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          GRANT USAGE ON SCHEMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          GRANT CREATE TABLE ON SCHEMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          GRANT CREATE VIEW ON SCHEMA ADVARRA_ONCORE_WORKSPACE.VIEWS_WORKSPACE TO ROLE ${{ env.SNOWSQL_CUST_NAME }}_ROLE;
          EOF
