name: User_creation_in_snowflake_reader_account

env:
  SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
  SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
  SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
  SNOWSQL_ROLE: ${{ secrets.SNOWSQL_ROLE }}

on:
  workflow_dispatch:

jobs:
  executequery:
    name: User_creation_in_snowflake_reader_account
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download SnowSQL
        run: curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.9-linux_x86_64.bash
      - name: Install SnowSQL
        run: SNOWSQL_DEST=~/snowflake SNOWSQL_LOGIN_SHELL=~/.profile bash snowsql-1.2.9-linux_x86_64.bash
      - name: Test installation
        run: ~/snowflake/snowsql -v
      - name: Variable Substitution
        run: echo "variable_substitution=true" | tee -a ~/.snowsql/config

      - name: Execute SQL against Snowflake
        env:
          FILE_LIST: ${{ secrets.FULL_FILE_LIST }}
          ROLES_LIST: ${{ secrets.roles_list }}
        run: |
          echo "$FILE_LIST"
          IFS="," read -ra emails <<< "$FILE_LIST"
          IFS="," read -ra roles <<< "$ROLES_LIST"
          for email in "${emails[@]}"; do
            password=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)

            ~/snowflake/snowsql -u "$SNOWSQL_USER" -o friendly -d "$SNOWSQL_ACCOUNT" -w "${SNOWSQL_ROLE}" -q "CREATE USER \"$email\" PASSWORD = '$password' MUST_CHANGE_PASSWORD = TRUE EMAIL = '$email';"
            for role in "${roles[@]}"; do
              ~/snowflake/snowsql -u "$SNOWSQL_USER" -o friendly -d "$SNOWSQL_ACCOUNT" -w "${SNOWSQL_ROLE}" -q "GRANT ROLE \"$role\" TO USER \"$email\";"
              echo "Role '$role' granted to user '$email'."
            done

            # Display password and role assignment for the newly created user
            echo "User created with email: $email"
            echo "Password: $password"
            echo "Roles assigned to user '$email': ${roles[@]}"
          done
